site_name: Yessi的个人网站
site_url: https://yessi-zzz.github.io/
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: images/YeIcon.png
  palette: 
    scheme: slate
    primary: orange
    accent: pink
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking # 追踪并高亮当前活动页面
    - navigation.tabs # 标签页导航，移动设备不显示
    - navigation.path
    - navigation.top # back to top 按钮
    - toc.follow
    - search.suggest # 搜索建议
    - search.highlight # 高亮搜索结果
    - navigation.indexes # 会有一个index页面,而不是打开tab的第一篇文章
    - navigation.expand # 核心功能：允许展开和收缩菜单

markdown_extensions:  # 支持数学公式 such as LaTeX, MathML, AsciiMath
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Yessi-zzz
    - icon: fontawesome/brands/bilibili
      link: https://https://space.bilibili.com/290156913?spm_id_from=333.40138.0.0
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - social:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/social
      cards: true
      log: true
      cards_dir: assets/images/social
      cards_layout_dir: layouts
      debug: true
      debug_on_build: false
      debug_grid: true
      debug_grid_step: 32
      debug_color: yellow
  - meta:
      enabled: true
  - blog:
      archive: false
  - tags
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

nav:
  - 我:
      - Yessi/index.md
      - 我的桌面: Yessi/我的桌面/myDesktop.md
  - Notes:
      - notes/index.md
      - Codes:
          - Finbonacci Sequence: notes/codes/Fibonacci Number.md
          - Knapsack Problem: notes/codes/Knapsack Problem.md

   